### ISSUE TITLE
Reading 2-dim array of udt

### ISSUE THREAD

**Issue by PedramK4** [NothinRandom/CoDeSys_EIP#11]
Would it be possible to read a two-dimensional array of type udt? udt_Test[i,j]
If so, could you please suggest arguments for bRead?

**Comment by NothinRandom** [comment]
@PedramK4,

Sorry for delayed response.  I don't have a controller in front of me, but I'll get to this once I locate one.

Thanks,

**Comment by NothinRandom** [comment]
Ok, it looks like the current code doesn't support multi-dimensional arrays.  I'm going to implement support for 2D and 3D arrays.

**Comment by NothinRandom** [comment]
@PedramK4,

Sorry for delay.  Was able to get my hands on a PLC and tested this on 1D (testArray[0]), 2D (testArray1[0,0]), and 3D (testArray2[0,0,0]).  Let me know if this works for you and feel free to raise issues.

**Comment by PedramK4** [comment]
Thank you very much!
