### ISSUE TITLE
TIMER UDT to CoDeSys STRUCT

### ISSUE THREAD

**Issue by NothinRandom** [NothinRandom/CoDeSys_EIP#6]
This is a bit strange because when I was first testing reading/write from Rockwell TIMER UDT to CoDeSys STRUCT, I just needed to declare 4B alignment and with the 5 bits padding but didn't use the 3 extra bytes.  However, it somehow changed so I need to pad with 3 extra bytes now...  further testing is needed here.  If some Rockwell expert can shed some light here, would be great

```
{attribute 'pack_mode' := '4'}

// NOTE: extremely important to have your bytes aligned correctly,
//      so read up on pack mode e.g. "{attribute 'pack_mode' := '0'}"
//      https://help.codesys.com/webapp/_cds_pragma_attribute_pack_mode;product=codesys;version=3.5.16.0

// It looks like timer must have padding?  Need to investigate this
TYPE stTimer :
STRUCT
    // EN is 0x80 (128); TT is 0x40 (64); DN is 0x20 (32)
    // bitwise:
    //  EN 10000000
    //  TT 01000000
    //  DN 00100000
    //PAD     : ARRAY [1..3] OF BYTE;
    PAD1    : BIT;
    PAD2    : BIT;
    PAD3    : BIT;
    PAD4    : BIT;
    PAD5    : BIT;
    DN      : BIT;
    TT      : BIT;
    EN      : BIT;
    PRE     : UDINT;
    ACC     : UDINT;
END_STRUCT
END_TYPE
```

**Comment by Zmotive** [comment]
Yep that looks correct. The bits do make up only 3bits of 1 byte, but the following DINTs make that 1 byte into 4. it is because it is a SINT followed by a DINT (or any 4 byte or greater element). AB will offset the SINT by 3 more so that the DINT Aligns. Even if they put the byte at the end of the stuct the definition would still be 12 bytes. This is Ztoka BTW :-)

**Comment by NothinRandom** [comment]
@Zmotive hehe, I figured.  Library was dedicated to you btw... I just couldn't wait on controls time anymore.

The weird thing is that it the padding commented out `//PAD     : ARRAY [1..3] OF BYTE;` used to work.  Something changed... somewhere, and now I need to add back in the bytes padding.  According to the CoDeSys pack mode, specifying 4B alignment means I shouldn't need this padding at all.  I'll take a look when time opens up, unless you want to take a stab at it first.

**Comment by NothinRandom** [comment]
Looks like padding of 3 bytes is needed; no way around it.  Closing ticket.
